name: Wheels

on:
  workflow_dispatch:
    inputs:
      MLIR_WHEEL_VERSION:
        description: 'mlir wheel version'
        type: string
        required: false
        default: ''
  workflow_call:
    inputs:
      MLIR_WHEEL_VERSION:
        description: 'mlir wheel version'
        type: string
        required: false
        default: ''

jobs:

  build:

    continue-on-error: true

    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - OS: ubuntu-20.04
            ARCH: x86_64

          # - OS: ubuntu-20.04
          #   ARCH: x86_64
          #   BUILD_CUDA: true

          # - OS: ubuntu-20.04
          #   ARCH: x86_64
          #   BUILD_VULKAN: true

          # - OS: ubuntu-20.04
          #   ARCH: x86_64
          #   BUILD_OPENMP: true

          - OS: windows-2019
            ARCH: AMD64

          # - OS: macos-12
          #   ARCH: x86_64

          # - OS: macos-12
          #   ARCH: arm64

          # - OS: macos-12
          #   ARCH: arm64
          #   BUILD_VULKAN: true

          # - OS: macos-12
          #   ARCH: arm64
          #   BUILD_OPENMP: true

    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github/actions

      - uses: ./.github/actions/setup_base
        id: setup_base
        with:
          MATRIX_OS: ${{ matrix.OS }}
          MATRIX_ARCH: ${{ matrix.ARCH }}

      - uses: ./.github/actions/setup_ccache
        id: setup_ccache
        with:
          MATRIX_OS: ${{ matrix.OS }}
          MATRIX_ARCH: ${{ matrix.ARCH }}
          EXTRA_KEY: ${{ matrix.BUILD_CUDA && 'cuda-' || '' }}${{ matrix.BUILD_VULKAN && 'vulkan-' || '' }}${{ matrix.BUILD_OPENMP && 'openmp' || '' }}

      # build

      - name: cibuildwheel python bindings
        shell: bash
        working-directory: ${{ steps.setup_base.outputs.WORKSPACE_ROOT }}
        run: |
          
          cp -R scripts python_bindings/scripts
          pushd python_bindings
          
          BUILD_CUDA=${{ matrix.BUILD_CUDA }} \
          BUILD_OPENMP=${{ matrix.BUILD_OPENMP }} \
          BUILD_VULKAN=${{ matrix.BUILD_VULKAN }} \
          CIBW_ARCHS=${{ matrix.ARCH }} \
          CMAKE_GENERATOR=Ninja \
          HOST_CCACHE_DIR=${{ steps.setup_ccache.outputs.HOST_CCACHE_DIR }} \
          MATRIX_OS=${{ matrix.OS }} \
          MLIR_WHEEL_VERSION=${{ inputs.MLIR_WHEEL_VERSION }} \
          cibuildwheel --output-dir ../wheelhouse
          
          popd

      - name: Download cache from container ubuntu
        if: matrix.OS == 'ubuntu-20.04' && (success() || failure())
        working-directory: ${{ steps.setup_base.outputs.WORKSPACE_ROOT }}
        shell: bash
        run: |
          
          ccache -s
          HOST_CCACHE_DIR="$(ccache --get-config cache_dir)"
          rm -rf $HOST_CCACHE_DIR
          mv ./wheelhouse/.ccache $HOST_CCACHE_DIR
          ls -la $HOST_CCACHE_DIR
          ccache -s

      # done

      - name: Upload wheels
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.setup_base.outputs.WORKSPACE_ROOT }}/wheelhouse/*.whl
          name: build_artifact_python_bindings

  build-linux-aarch64:

    continue-on-error: true

    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - OS: ubuntu-20.04
            ARCH: aarch64
            PY_VERSION: "cp38"

          - OS: ubuntu-20.04
            ARCH: aarch64
            PY_VERSION: "cp39"

          - OS: ubuntu-20.04
            ARCH: aarch64
            PY_VERSION: "cp310"

          - OS: ubuntu-20.04
            ARCH: aarch64
            PY_VERSION: "cp311"

          - OS: ubuntu-20.04
            ARCH: aarch64
            PY_VERSION: "cp312"

    steps:
      - name: Checkout actions
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            .github/actions

      - uses: ./.github/actions/setup_base
        id: setup_base
        with:
          MATRIX_OS: ${{ matrix.OS }}
          MATRIX_ARCH: ${{ matrix.ARCH }}

      - uses: ./.github/actions/setup_ccache
        id: setup_ccache
        with:
          MATRIX_OS: ${{ matrix.OS }}
          MATRIX_ARCH: ${{ matrix.ARCH }}

      - name: Set up QEMU
        if: ${{ matrix.OS == 'ubuntu-20.04' && matrix.ARCH == 'aarch64' }}
        uses: docker/setup-qemu-action@v2
        with:
          platforms: ${{ matrix.ARCH }}

      # build

      - name: cibuildwheel python bindings aarch64
        shell: bash
        working-directory: ${{ steps.setup_base.outputs.WORKSPACE_ROOT }}
        run: |
          
          cp -R scripts python_bindings/scripts
          pushd python_bindings
          
          BUILD_CUDA=${{ matrix.BUILD_CUDA }} \
          BUILD_OPENMP=${{ matrix.BUILD_OPENMP }} \
          BUILD_VULKAN=${{ matrix.BUILD_VULKAN }} \
          CIBW_ARCHS=${{ matrix.ARCH }} \
          CIBW_BUILD=${{ matrix.PY_VERSION }}-manylinux_aarch64 \
          CIBW_CONTAINER_ENGINE="docker; create_args: --platform=linux/aarch64" \
          CMAKE_GENERATOR=Ninja \
          HOST_CCACHE_DIR=${{ steps.setup_ccache.outputs.HOST_CCACHE_DIR }} \
          MATRIX_OS=${{ matrix.OS }} \
          MLIR_WHEEL_VERSION=${{ inputs.MLIR_WHEEL_VERSION }} \
          cibuildwheel --output-dir ../wheelhouse
          
          popd

      - name: Download cache from container ubuntu
        if: success() || failure()
        working-directory: ${{ steps.setup_base.outputs.WORKSPACE_ROOT }}
        shell: bash
        run: |
          
          ccache -s
          HOST_CCACHE_DIR="$(ccache --get-config cache_dir)"
          rm -rf $HOST_CCACHE_DIR
          mv ./wheelhouse/.ccache $HOST_CCACHE_DIR
          ls -la $HOST_CCACHE_DIR
          ccache -s

      - name: Reset datetime ccache
        working-directory: ${{ steps.setup_base.outputs.WORKSPACE_ROOT }}
        shell: bash
        run: |
          
          ccache -s
          HOST_CCACHE_DIR="$(ccache --get-config cache_dir)"
          DATETIME=$(date +"%Y%m%d%H")
          find $HOST_CCACHE_DIR -exec touch -a -m -t "$DATETIME""00" {} \;
          ccache -s

      # done

      - name: Upload wheels
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          path: ${{ steps.setup_base.outputs.WORKSPACE_ROOT }}/wheelhouse/*.whl
          name: build_artifact_python_bindings

  upload_bindings_wheels:

    needs: [build, build-linux-aarch64]

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: build_artifact_python_bindings
          path: dist

      - name: Release current commit
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "dist/*.whl"
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "latest"
          name: "latest"
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true

      - name: Release current commit
        uses: ncipollo/release-action@v1.12.0
        with:
          owner: omontfort
          repo: wheels
          artifacts: "dist/*.whl"
          token: "${{ secrets.WHEELS_REPO }}"
          tag: "i"
          name: "i"
          removeArtifacts: false
          allowUpdates: true
          replacesArtifacts: true
          makeLatest: true
